<?php

declare(strict_types=1);

namespace Jmonitor;

/**
 * Resolves the installed version of this package at runtime.
 *
 * @internal
 */
final class Version
{
    /**
     * Sent when the version cannot be resolved. Never an empty string: the Jmonitor
     * server rejects a request whose X-JMONITOR-VERSION header is empty.
     */
    public const FALLBACK = 'unknown';

    private const PACKAGE = 'jmonitor/collector';

    /**
     * @param string $package Only meant to be overridden in tests
     */
    public static function get(string $package = self::PACKAGE): string
    {
        // Composer\InstalledVersions is generated by Composer 2. It is missing when the
        // vendor directory was not built by Composer at all (hand-made autoloader, partial
        // deployment archive…), a case no composer.json requirement can protect against.
        if (class_exists(\Composer\InstalledVersions::class)) {
            try {
                $version = \Composer\InstalledVersions::getPrettyVersion($package);
            } catch (\OutOfBoundsException $e) {
                // Package not registered in the installed map.
                $version = null;
            }

            if ($version !== null && $version !== '') {
                return $version;
            }
        }

        return self::FALLBACK;
    }
}
